language: java

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - sh -e /etc/init.d/xvfb start
  - sudo R CMD javareconf
  - ./travis-tool.sh aptget_install r-cran-xml 
  - ./travis-tool.sh aptget_install r-cran-gplots
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github ramnathv/slidify@dev
  - ./travis-tool.sh install_github ramnathv/slidifyLibraries@dev
  - ./travis-tool.sh install_github cboettig/knitcitations
  - ./travis-tool.sh install_github trinker/reports
  - ./travis-tool.sh install_github trinker/qdapDictionaries
  - ./travis-tool.sh install_deps
  - Rscript -e "source('http://bioconductor.org/biocLite.R');
      biocLite();
      biocLite('Rgraphviz')"
script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change

env:
   global:
     - R_BUILD_ARGS="--resave-data=best" 
     - DISPLAY=:99.0
