language: c
# To build on OSX, switch the previous line to
# language: objective-c

script: ./travis-tool.sh run_tests

before_install:
    - cp scripts/travis-tool.sh qdap
    - cd qdap
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - ./travis-tool.sh install_deps
