language: java

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - ./travis-tool.sh bootstrap
install:
  - sh -e /etc/init.d/xvfb start
  - sudo R CMD javareconf
  - ./travis-tool.sh install_r_binary xml
  - ./travis-tool.sh install_r_binary gplots
  - ./travis-tool.sh install_r_binary rjava
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github trinker/qdapTools
  - ./travis-tool.sh install_github trinker/qdapDictionaries
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests
notifications:
  email:
    on_success: change
    on_failure: change
env:
   global:
     - R_BUILD_ARGS="--compact-vignettes=gs+qpdf --resave-data=best"
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1
