language: r

sudo: false
before_install:
  - sh -e /etc/init.d/xvfb start

addons:
  apt:
    packages:
    - qpdf
    - texinfo
      
r_github_packages: 
  
notifications:
  email:
    on_success:      change
    on_failure:      change
    

r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

env:
   global:
     - DISPLAY=:99.0
     - BOOTSTRAP_LATEX=1




